name: 'Setup Node.js Environment'
description: 'Setup Node.js with caching and install project dependencies'
inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '20'
  cache:
    description: 'Cache type to use (npm, yarn, pnpm)'
    required: false
    default: 'npm'
  install-dependencies:
    description: 'Whether to install dependencies'
    required: false
    default: 'true'
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.cache }}

    - name: Install dependencies
      if: inputs.install-dependencies == 'true'
      shell: bash
      run: npm ci
