name: 'Checkout Repository'
description: 'Standardized repository checkout with security pinning'
inputs:
  ref:
    description: 'The branch, tag or SHA to checkout'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        ref: ${{ inputs.ref }}
