name: 'Setup Complete Environment'
description: 'Complete environment setup including checkout, Node.js, dependencies, and EAS CLI'
inputs:
  expo-token:
    description: 'EXPO_TOKEN secret value'
    required: true
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '20'
  cache:
    description: 'Cache type to use (npm, yarn, pnpm)'
    required: false
    default: 'npm'
  ref:
    description: 'The branch, tag or SHA to checkout'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: ./.github/actions/checkout
      with:
        ref: ${{ inputs.ref }}

    - name: Setup Node.js and dependencies
      uses: ./.github/actions/setup-node
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.cache }}

    - name: Setup EAS
      uses: ./.github/actions/setup-eas
      with:
        expo-token: ${{ inputs.expo-token }}
