name: CI Pipeline
on:
  push:
    branches: [ "main", "master", "develop" ]
    paths:
      - 'src/**'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
      - 'biome.json'
  pull_request:
    branches: [ "main", "master", "develop" ]
    paths:
      - 'src/**'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
      - 'biome.json'
jobs:
  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci

    - name: TypeScript type checking
      run: npx tsc --noEmit
    - name: Biome linter check
      run: npx @biomejs/biome lint src/
      continue-on-error: false
    - name: Biome formatter check
      run: npx @biomejs/biome format --write=false src/
      continue-on-error: false
    - name: Check for unused dependencies
      run: |
        # Check if there are any unused dependencies
        if command -v depcheck &> /dev/null; then
          npx depcheck --ignores="@types/*,jest*,@babel/*"
        else
          echo "Skipping dependency check (depcheck not available)"
        fi
      continue-on-error: true
  # Optional: Add tests when they exist
  # test:
  #   name: Run Tests
  #   runs-on: ubuntu-latest
  #   needs: code-quality
  #   
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4
  #   
  #   - name: Setup Node.js
  #     uses: actions/setup-node@v4
  #     with:
  #       node-version: '18'
  #       cache: 'npm'
  #   
  #   - name: Install dependencies
  #     run: npm ci
  #   
  #   - name: Run tests
  #     run: npm test -- --coverage --watchAll=false