name: iOS Submit to App Store

# Explicit permissions for security
permissions:
  contents: read
  actions: read
  id-token: write

on:
  workflow_dispatch:
    inputs:
      submit_latest:
        description: 'Submit latest production build to App Store'
        required: false
        default: true
        type: boolean

jobs:
  submit:
    name: Submit Latest Production Build to App Store
    runs-on: ubuntu-latest
    environment: production
    if: ${{ github.event.inputs.submit_latest == true }}
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: 'lts/*'
          cache: npm

      - name: Setup EAS
        uses: expo/expo-github-action@c7b66a9c327a43a8fa7c0158e7f30d6040d2481e # v8.2.1
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          packager: npm
          expo-cache: false
          eas-cache: false

      - name: Submit latest production build to App Store
        env:
          EAS_NO_VCS: 1
        run: |
          echo "Submitting latest iOS production build to App Store..."

          # Submit latest production build directly
          eas submit --platform ios --latest --non-interactive 2>&1 | \
            sed 's/Serial Number.*/Serial Number             [REDACTED]/g' | \
            sed 's/Apple Team.*/Apple Team                [REDACTED]/g' | \
            sed 's/Developer Portal ID.*/Developer Portal ID       [REDACTED]/g' | \
            sed 's/Bundle Identifier.*/Bundle Identifier         [REDACTED]/g'
